services:
  postgres:
    image: postgres:16
    container_name: toole_postgres
    restart: always
    environment:
      POSTGRES_USER: a
      POSTGRES_PASSWORD: a
      POSTGRES_DB: toole_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

